<html>
	<head>
		<link rel="stylesheet" type="text/css" href="./include/style.css" />
	</head>

<body>


<table class="header" ><tr>
	<td style="width: 0%">
		<a href="./index.php">
			<img src="./docs/logo_small.png" />
		</a>
	</td>
	<td style="width: 100%">
	
<div class="nav">
	<a href="./index.php">Home</a>
	<a href="./products.php">Products</a>
	<a href="./presentations.php">Presentations</a>
	<a href="./about.php">About Us</a>
	<a href="./contact.php">Contact Us</a>
	<!--<a href="./partners.php">Partners</a>-->
</div>
<div class="title">	
	<h1 style="margin-bottom: 0px;">Sino-American Pigment Systems, Inc.</h1>
	<h4>High-Performance, Non-Toxic, Hybrid Pigments</h4>
</div>
</td>
</tr></table>

<div class="main">
